[package]
name = "lazy-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4_flex = "0.11.1"
walkdir = "2.3.3"
tar = "0.4.40"